### ISSUE TITLE
Not working on OpenELEC 5.01

### ISSUE THREAD

**Issue by jonashilmersson** [steeve/plugin.video.pulsar#102]
Pulsar doesn't work anymore after upgrading to OpenELEC 5.01. I'm running v0.4.5 and get script failed errors when trying to start streaming.

**Comment by epoxi** [comment]
Same here. It keeps displaying "You must restat XBMC before using Pulsar".

**Comment by kero99** [comment]
Confirmed:

Pulsar 0.4.5
OpenELEC 5.01
Raspberry Pi B+

Loop restarting pulsar after first reboot...

**Comment by steeve** [comment]
Can you provide a debug log ? Can't do nothing without it...

**Comment by alexis-boisserand** [comment]
Same problem here. Here is a debug log: http://xbmclogs.com/show.php?id=419172

**Comment by NoGood** [comment]
I am using 
Pulsar 0.4.5
OpenELEC 5.01

Without a problem. not running on raspberry pi though

**Comment by epoxi** [comment]
Updated OpenELEC and Pulsar to a new version, still the same problem:

Pulsar 0.4.6
OpenELEC 5.03
Raspberry Pi B+

Kodi Log --> https://gist.github.com/epoxi/fd7ea2703dd1b5fc605c

**Comment by jonashilmersson** [comment]
I updated OpenELEC and Pulsar to a new version:

* Pulsar 0.4.6
* OpenELEC 5.03

Now Pulsar tells me that XBMC must be restarted, and it doesn't help to reboot the PI.

Brgds

Jonas

**Comment by steeve** [comment]
Guys, how are you downloading the addon? I hope not from the Github "Download ZIP" on the right.

Use the releases provided at: https://github.com/steeve/plugin.video.pulsar/releases/

That's what your logs tell me

**Comment by Prophecy67** [comment]
@steeve I'm getting looping errors on the latest 0.4.7 version (openelec 5.0.1). Cannot start Pulsar at all

18:06:01 T:3043266560  NOTICE: Previous line repeats 1 times.
18:06:01 T:3043266560   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/
18:06:01 T:3043266560   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
18:06:04 T:3043266560   ERROR: GetDirectory - Error getting addons://sources/video/
18:06:04 T:3043266560   ERROR: CGUIMediaWindow::GetDirectory(addons://sources/video/) failed
18:06:04 T:3043266560  NOTICE: SpawnThread - fatal error creating thread
18:06:32 T:3043266560  NOTICE: Previous line repeats 2 times.
18:06:32 T:3043266560   ERROR: GetDirectory - Error getting addons://sources/video/
18:06:32 T:3043266560   ERROR: CGUIMediaWindow::GetDirectory(addons://sources/video/) failed
18:06:32 T:3043266560  NOTICE: SpawnThread - fatal error creating thread
18:07:04 T:3043266560  NOTICE: Previous line repeats 1 times.
18:07:04 T:3043266560   ERROR: GetDirectory - Error getting addons://all/
18:07:04 T:3043266560   ERROR: CGUIMediaWindow::GetDirectory(addons://all/) failed
18:07:04 T:3043266560  NOTICE: SpawnThread - fatal error creating thread

**Comment by jonashilmersson** [comment]
Got the latest version v.0.47 automatically downloaded from the repo, and it still says "You must restart XBMC before using Pulsar." Rebooting doesn't help unfortunately.

**Comment by epoxi** [comment]
@steeve, I've now downladed Pulsar from the link you provided (https://github.com/steeve/plugin.video.pulsar/releases/)

The outcome was almost the same. But now it keeps crashing and reloading :(

Upgraded OpenELEC to 5.04

Pulsar 0.4.7
OpenELEC 5.04
Raspberry Pi B+

**Comment by jonashilmersson** [comment]
Hi,

I have also upgraded to OpenELEC 5.04 and Pulsar 0.4.7, still the same message to restart XBMC.

Brgds

Jonas

**Comment by kodispot** [comment]
I Have The Same Issue with Gotham OpenELEC In Mx2 Box..

**Comment by asfaltboy** [comment]
@steeve - The logs above seem to indicate that the error tends to occur after the [`get_pulsar_checksum` method](https://github.com/steeve/plugin.video.pulsar/blob/master/resources/site-packages/pulsar/daemon.py#L33:L36); the exception might indicate wrong (out of bounds) fd position or argument value (taken [from here](http://stackoverflow.com/a/2724071/484127)).

I don't have the issue yet, per se, but I will be testing the addon on an OpenELEC later tonight (finally hooking up my RaspberryPi 2 up).

**Comment by steeve** [comment]
ok, apparently you guys have a corrupted install.

try this, in OpenELEC shell:
```sh
$ rm -rf .kodi/addons/plugin.video.pulsar .kodi/userdata/addon_data/plugin.video.pulsar
```

And then reinstall Pulsar from the zip at https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip

**Comment by epoxi** [comment]
Did what you mention, and reinstalled... Pulsar keeps restarting

17:49:46 T:1690297408  NOTICE: [plugin.video.pulsar] pulsard: starting
pulsard
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main                          .__
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             ______  __ __|  |   ___________ _______
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             \____ \|  |  \  |  /  ___/\__  \\_  __ \
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             |  |_> >  |  /  |__\___ \  / __ \|  | \/
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             |   __/|____/|____/____  >(____  /__|
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             |__|                   \/      \/
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  main             Version: 0.4.7 Git: v0.4.7 Go: go1.4
17:49:47 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
 INFO  config           Reloading configuration...
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
 INFO  main             Addon: plugin.video.pulsar v0.4.7
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
 INFO  btservice        Setting Session settings...
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
 INFO  btservice        Setting Encryption settings...
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
 INFO  btservice        Consuming alerts...
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] panic: dial tcp
127.0.0.1:9090: connection refused
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar]
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] goroutine 1 [running]:
17:49:48 T:1690297408  NOTICE: [plugin.video.pulsar] pulsard: starting
pulsard


On Mon, Mar 2, 2015 at 5:36 PM, Steeve Morin <notifications@github.com>
wrote:

> ok, apparently you guys have a corrupted install.
>
> try this, in OpenELEC shell:
>
> $ rm -rf .kodi/addons/plugin.video.pulsar .kodi/userdata/addon_data/plugin.video.pulsar
>
> And then reinstall Pulsar from the zip at
> https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-76813392>
> .
>



-- 
Atte.-
LC

**Comment by steeve** [comment]
Yes because you didn't follow the install guide and didn't enable remote
control in Kodi

On Tuesday, March 3, 2015, Lucas Campa <notifications@github.com> wrote:

> Did what you mention, and reinstalled... Pulsar keeps restarting
>
> 17:49:46 T:1690297408 NOTICE: [plugin.video.pulsar] pulsard: starting
> pulsard
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main .__
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main ______ __ __| | ___________ _______
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main \____ \| | \ | / ___/\__ \\_ __ \
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main | |_> > | / |__\___ \ / __ \| | \/
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main | __/|____/|____/____ >(____ /__|
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main |__| \/ \/
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO main Version: 0.4.7 Git: v0.4.7 Go: go1.4
> 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> INFO config Reloading configuration...
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> INFO main Addon: plugin.video.pulsar v0.4.7
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> INFO btservice Setting Session settings...
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> INFO btservice Setting Encryption settings...
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> INFO btservice Consuming alerts...
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] panic: dial tcp
> 127.0.0.1:9090: connection refused
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar]
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] goroutine 1 [running]:
> 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] pulsard: starting
> pulsard
>
>
> On Mon, Mar 2, 2015 at 5:36 PM, Steeve Morin <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > ok, apparently you guys have a corrupted install.
> >
> > try this, in OpenELEC shell:
> >
> > $ rm -rf .kodi/addons/plugin.video.pulsar
> .kodi/userdata/addon_data/plugin.video.pulsar
> >
> > And then reinstall Pulsar from the zip at
> >
> https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-76813392
> >
> > .
> >
>
>
>
> --
> Atte.-
> LC
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-77031899>
> .
>


-- 
Steeve Morin
twitter.com/steeve
github.com/steeve
linkd.in/smorin

**Comment by epoxi** [comment]
Clean reinstall, erasing all ./kodi pulsar files.

OpenELEC:~ # rm -rf .kodi/addons/plugin.video.pulsar
.kodi/userdata/addon_data/plugin.video.pulsar
OpenELEC:~ # cd .kodi/addons/plugin.video.pulsar
-sh: cd: can't cd to .kodi/addons/plugin.video.pulsar
OpenELEC:~ # cd .kodi/userdata/addon_data/plugin.video.pulsar
-sh: cd: can't cd to .kodi/userdata/addon_data/plugin.video.pulsar
OpenELEC:~ #

- Both remote control options are selected.

- Re-Downloaded the pulsar plugin from the provided link. (
https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip
)

- Installed plugin from System --> Settings --> Add-ons --> Install from
zip file (popup indicates "addon enabled")

- Reboot system/Kodi


ON REBOOT

- Try to exec Pulsar for the first time. A pop-up says "you must reboot
kodi/xbmc"

- Reboot system/Kodi


ON SECOND REBOOT

- Try to exec Pulsar for the second time. A pop-up says "error: script
failed" then "pulsar daemon restarted"

- BUT it worked on a second try :)


A lil' slow on a RBPi B+, but is really neat and functional :D

Thanks Steeve!











On Tue, Mar 3, 2015 at 7:07 PM, Steeve Morin <notifications@github.com>
wrote:

> Yes because you didn't follow the install guide and didn't enable remote
> control in Kodi
>
>
> On Tuesday, March 3, 2015, Lucas Campa <notifications@github.com> wrote:
>
> > Did what you mention, and reinstalled... Pulsar keeps restarting
> >
> > 17:49:46 T:1690297408 NOTICE: [plugin.video.pulsar] pulsard: starting
> > pulsard
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main .__
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main ______ __ __| | ___________ _______
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main \____ \| | \ | / ___/\__ \\_ __ \
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main | |_> > | / |__\___ \ / __ \| | \/
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main | __/|____/|____/____ >(____ /__|
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main |__| \/ \/
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO main Version: 0.4.7 Git: v0.4.7 Go: go1.4
> > 17:49:47 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:47
> > INFO config Reloading configuration...
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> > INFO main Addon: plugin.video.pulsar v0.4.7
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> > INFO btservice Setting Session settings...
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> > INFO btservice Setting Encryption settings...
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] 2015-03-03 20:49:48
> > INFO btservice Consuming alerts...
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] panic: dial tcp
> > 127.0.0.1:9090: connection refused
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar]
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] goroutine 1
> [running]:
> > 17:49:48 T:1690297408 NOTICE: [plugin.video.pulsar] pulsard: starting
> > pulsard
> >
> >
> > On Mon, Mar 2, 2015 at 5:36 PM, Steeve Morin <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > wrote:
> >
> > > ok, apparently you guys have a corrupted install.
> > >
> > > try this, in OpenELEC shell:
> > >
> > > $ rm -rf .kodi/addons/plugin.video.pulsar
> > .kodi/userdata/addon_data/plugin.video.pulsar
> > >
> > > And then reinstall Pulsar from the zip at
> > >
> >
> https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> >
> https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-76813392
> > >
> > > .
> > >
> >
> >
> >
> > --
> > Atte.-
> > LC
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-77031899
> >
> > .
> >
>
>
> --
> Steeve Morin
> twitter.com/steeve
> github.com/steeve
> linkd.in/smorin
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/steeve/plugin.video.pulsar/issues/102#issuecomment-77046947>
> .
>



-- 
Atte.-
LC

**Comment by pakamon** [comment]
Same here.
- Raspberry Pi B
- OpenElec 5.0.6
- Pulsar plugin: https://github.com/steeve/plugin.video.pulsar/releases/download/v0.4.7/plugin.video.pulsar-0.4.7.zip

**Comment by myssing** [comment]
Please check out my comment in
https://github.com/steeve/plugin.video.pulsar/issues/118

**Comment by jonashilmersson** [comment]
Hi,

I had to reinstall my PI with a new OpenELEC 5.0.6 for other reasons (the Confluence interface was corrupt), and now Pulsar 0.4.7 works fine. 

Brgds

Jonas

**Comment by steeve** [comment]
May I close this, then ?

**Comment by jonashilmersson** [comment]
Ok for me :-)

**Comment by lilp69** [comment]
Hi, I use Openelec 5.0.3 on Rpi2, I download the repository 1.0.1, but when I want download Pulsar from the repository I always have a fail.

**Comment by burekas7** [comment]
Hi,
What is the solution for the message "you must restart xbmc before using pulsar" in Kodi 15.1 insengrad even after restarting kodi?
I have already uninstall several times include the providers, delete all the related folders, and install again (by the way it works only with install from zip from here), and again and again the same problem.
- I'm using Windows7 as OS, and it worked with Kodi 14.2

**Comment by zorglub76** [comment]
I've had the same message on Raspberry Pi 2. I tried reinstalling Openelec with beta version, but the same message kept appearing ("you must restart....."). And then I noticed that I downloaded the whole pulsar repository (master), instead a particular version (https://github.com/steeve/plugin.video.pulsar/releases). I uninstalled Pulsar, installed from the new file, and it worked like a charm.

**Comment by burekas7** [comment]
@zorglub76 
Thanks man!
Now it works.
