### ISSUE TITLE
Can not play more than one file without having to restart Kodi

### ISSUE THREAD

**Issue by grandixximo** [steeve/plugin.video.pulsar#103]
On kodi 14.1
I can play my first tv show episode without any problems, i stop the show because i finish watching it, and i go to download the second show, the second episode never starts successfully, it always gets stuck in the buffering process.

i made a log here

http://pastebin.com/fLcLPa1r

The program didn't crash it just throw me an error that it couldn't play the file, and the download is stuck, if i cancel is stuck at cancelling, i have no choice but to restart kodi, then i go for playing the same exact episode, and it plays fine, at the next episode i have to quit kodi and start again to be able to play the next episode, super annoying please get this fixed :)

**Comment by steeve** [comment]
Can you try with v0.4.7 ? Thanks

**Comment by grandixximo** [comment]
it works just fine on 0.4.7, thank you so much :+1:

**Comment by steeve** [comment]
Awesome :)
