### ISSUE TITLE
No Links Found/Blocked by Filename 

### ISSUE THREAD

**Issue by TSM-EVO** [steeve/plugin.video.pulsar#113]
Hi,
I've recently moved from OSMC to OpenELEC on my RPi2, and I am having real issues getting Pulsar to play any TV show. I've run into two distinct errors in the logs that I can see, the most pertinent one being that it appears a string is being appended on to all outgoing search links. 

Loglines like this:
`
11:47:14 T:1484776512  NOTICE: [script.pulsar.TOTALLYLEGITPROVIDER-mc] https://TOTALLEYLEGITBAY.se/search/SHOW%20NAME%20s01e05%20%23tv%26filter/0/99/200`

The issue being the `#tv&filter`

I can see on the screen, in the notification that pops up for each provider there is the text #tv&filter

http://xbmclogs.com/pyvxohm00
http://xbmclogs.com/p0j4gmcqm

I tried an older version of Pulsar, 0.31, which is what all the providers say "ONLY SUPPORTS", still the same issue.

I'm going to try an older version of ELEC.

**Comment by steeve** [comment]
From what I'm reading, your provider is filtering out the links by itself, sending nothing to Pulsar

**Comment by TSM-EVO** [comment]
That's what it looks like to me too. I was going through the provider setup documentation, but it's a bit above my level. Thanks for the help. I don't suppose you could direct me to someone who is familiar with the providers? I think that my next step needs to be finding someone who can answer why the providers are all doing this.
