### ISSUE TITLE
Getting "You must restart XBMC before using Pulsar"

### ISSUE THREAD

**Issue by pakamon** [steeve/plugin.video.pulsar#118]
Hi,

I am getting following message over and over again after installing Pulsar plugin from zip (downloaded from GitHub) - Box restarted multiple times but still getting the same:

"You must restart XBMC before using Pulsar"

Pulsar plugin version: v0.4.7
Hardware: Raspberry Pi , OpenELEC + XBMC Gotham

OpenELEC:~/.xbmc/temp # tail -f xbmc.log shows:

16:11:12 T:2673865808  NOTICE: Thread JobWorker start, auto delete: true
16:11:12 T:2642408528  NOTICE: Thread LanguageInvoker start, auto delete: false
16:11:13 T:2642408528  NOTICE: -->Python Interpreter Initialized<--
16:11:15 T:3059586032   ERROR: GetDirectory - Error getting plugin://plugin.video.pulsar/
16:11:15 T:3059586032   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.pulsar/) failed
16:11:16 T:2642408528  NOTICE: Thread BackgroundLoader start, auto delete: false

Trying to figure out wtf without success :(

Regards,
pakamon

**Comment by myssing** [comment]
Check out: http://kodi.wiki/view/JSON-RPC_API
Make sure that these settings are enabled to fix the restart message
...
TCP: In System/Settings/Network/Services activate
- Allow programs on this system to control XBMC
- Allow programs on other systems to control XBMC
...

**Comment by pakamon** [comment]
Below options are enabled :
Allow programs on this system to control XBMC
Allow programs on other systems to control XBMC

Sadly no improvement.. still getting the same error message :(

**Comment by steeve** [comment]
@pakamon can you provide a debug log ? a full one, that is
i cannot help you without one

**Comment by pakamon** [comment]
Hi steeve,

I have decided to reinstall OpenELEC from scratch and install OpenELEC 5.0.6 (Kodi HELIX).
Then I have installed v0.4.7 Pulsar plugin and it works like a charm. 
Sadly I haven't collected debug logss before reinstalling :(

Thanks for all your help guys!
Cheers!

**Comment by burekas7** [comment]
Hi,
What is the solution for the message "you must restart xbmc before using pulsar" in Kodi 15.1 insengrad even after restarting kodi?
I have already uninstall several times include the providers, delete all the related folders, and install again (by the way it works only with install from zip from here), and again and again the same problem.
- I'm using Windows7 as OS, and it worked with Kodi 14.2

**Comment by muelles** [comment]
I have the same problem 
I'm using android with isengard 15.1 in minix h8plus

**Comment by rainmanone** [comment]
same problem here:
Windows 8.1 (bing edition) 64 bits
isengard 15.0 , 15.1 or 16.0
new install --> I get the restart request (Kodi is completely blank except from Pulsar)
upgrade from 14.2 (with all the add ons) --> I get in the Log: [Errno 10061] No connection could be made because the target machine actively refused it

**Comment by ShinobiX9X** [comment]
Hi,

Still nobody fixed this with success?
i had it after an upgrade. I think it was from Kodi 15.0 to 15.1.
On windows 10 64bit, Kodi 15.1

Would be happy to see the solution

**Comment by fabrizio5680** [comment]
Same issue on Android with Kodi 15.1

**Comment by julpec** [comment]
Same issue on Apple TV (iOS 6.1.4) with Kodi (14.2)

**Comment by zeemeer** [comment]
Same issue with me

**Comment by yanivz** [comment]
same with me. is there a solution without reinstalling?

**Comment by Tyvain** [comment]
same for me on cubox

**Comment by Gotcha007** [comment]
Same issue here too :-(
Kodi 16.0 Nvidia Shield android tv

**Comment by tylnesh** [comment]
Same here. Current OSMC on RPI3

**Comment by angel-luis** [comment]
Same issue here, Android 5.1.1 and latest version of Kodi (custom CM ROM).

**Comment by frozen-cdn** [comment]
Same issue here using OpenElec 6.0.3 on Raspberry Pi 3.

No amount of reboots or reinstallation fixes the issue.  Constantly complains about Kodi needing a restart even after several.
