### ISSUE TITLE
Pulsar on Raspberry Pi 2

### ISSUE THREAD

**Issue by lovemypi** [steeve/plugin.video.pulsar#120]
Hi there,
I've download repository.pulsarunofficial-1.0.1.zip. From Kodi > System > Install from Zip got that addon enabled. But when I went to Get-Addons > repository.pulsarunofficial-1.0.1 > click on that I did not see Video Addon even I did a force to refresh, reboot my Raspberry. I did enable "Allow programs on other system to control XBMC" and "Allow programs on other system to control XBMC" as well. Do I miss anything?
Thanks

**Comment by steeve** [comment]
hi, i can't support alternative methods for installing pulsar.
if you want to be sure, download it from the releases page at  https://github.com/steeve/plugin.video.pulsar/releases
