### ISSUE TITLE
Can't launch Pulsar (Always need a reboot message)

### ISSUE THREAD

**Issue by raspdealer** [steeve/plugin.video.pulsar#128]
Hey,
I've reboot but the message is still the same.

http://pastebin.com/z1kxLytF

Thankq

**Comment by Niwreg** [comment]
Same issue here. The control settings are both enabled. Tried to reboot whole device and restart kodi 

OS is osmc

**Comment by LaChoz** [comment]
Same here kodi 14.2

**Comment by LaChoz** [comment]
Now launching but says i don't hqve enough space when I have tons...

**Comment by raspdealer** [comment]
Ok for me with the updated repo
