### ISSUE TITLE
Subtitles do not work on OSMC

### ISSUE THREAD

**Issue by Loewkie** [steeve/plugin.video.pulsar#151]
I have a hard time getting subtitles to work in Pulsar. I'm using the opensubtitles service and it is working fine within other video add ons, but it does not seem to be working within Pulsar.

[Log file](http://xbmclogs.com/pkhlcx8av)

Everything else about Pulsar is amazing, and I'm really hoping that this can be fixed/solved. If that can be done, I would finally have a service that could stream HD, find subtitles and scrobble my movies and tv shows to Trakt.

**Comment by ehoood** [comment]
Hi, I can see you closed this issue.
Did you solve it? I am having exactly this issue

**Comment by NerosTie** [comment]
Same issue. This should be re-opened.
