### ISSUE TITLE
No Providers in Android 4.x

### ISSUE THREAD

**Issue by alexandrev** [steeve/plugin.video.pulsar#174]
I tried to use Pulsar for my MINIX NEO X8-H installed inside a Kodi 15.x version (previously I tried with a 14.x version with the same reuslt).

Everything is working fine until I try to select any movie or episode from a tv show. When I click I'm always get the "Unable to find providers".

Any help? 

Thanks!

**Comment by iocanel** [comment]
Have u installed any?

**Comment by alexandrev** [comment]
I've been checking the configuration and I didn't find any configuration setting to specify the provider. So, I don't know what are you talking about. Could you be more specific about the steps I have to do to enable one specify provider? Thanks in advance.

**Comment by alexandrev** [comment]
After reading the documentation I just discovery what you meant with your comment :). So I close the issue until I start any provider plug-in and see if everything is working as expected. Sorry for disturbing you and don't RTFM!
