### ISSUE TITLE
Pulsar not working with new FireTV

### ISSUE THREAD

**Issue by David-Alton** [steeve/plugin.video.pulsar#180]
Users are getting a message that they need to restart XBMC

**Comment by D-Kalck** [comment]
I have the same problem with Xbian on a Raspberry Pi 2.

**Comment by byron78** [comment]
Can confirm this is also an issue on the Nvidia Shield TV as well. 

Stuck in a "You Must Restart XBMC" loop. 

Tried deleting userdata/cache. 

Made sure all the necessary control settings are checked. 

Nothing fixes this. 

(Obviously a reboot doesn't either).

**Comment by byron78** [comment]
Update:

I think this may be related to the HTTP remote control port and the 15.2 version of Kodi I'm using. 

I can't change to port 80 on my Shield TV for some reason (so I'm guessing other android devices can't either) - by default I'm using port 8080. 

It looks like others who have had this issue solved it by reverting to port 80. 

As I said, unable to do that myself.

**Comment by Qmade** [comment]
same here with minix z64 android device...

cant change port either...

**Comment by adapan-bak** [comment]
Using and Nvidia Shield TV and I have the same issue as byron87.

**Comment by lvsas** [comment]
Same with my Nvidia Shield Android TV !

**Comment by ykhehra1** [comment]
I don't think it works with any android plateform

**Comment by adwani** [comment]
pulsar is working in my firetv stick i suggest deleting kodi completely then install it worked for me  if you delete the data only won't work.

**Comment by David-Alton** [comment]
@adwani Is it the new FireTV stick?
