### ISSUE TITLE
IMDB watchlist

### ISSUE THREAD

**Issue by bite-your-idols** [steeve/plugin.video.pulsar#192]
Hi!
Is there any option to include in Pulsar menu a link to my public IMDB watchlist?
I am trying to find where is in the source code the "IMDB TOP 250" code lines to try to edit them but I can not find it...

thanks!

**Comment by HacktionMan** [comment]
I use another Kodi addon for this. "Pulsar IMDB subscription"

**Comment by bite-your-idols** [comment]
Finally, I installed that addon and it works like a charm!!!

thanks!
