### ISSUE TITLE
Will the whole Go code ever be published?

### ISSUE THREAD

**Issue by ravishi** [steeve/plugin.video.pulsar#31]
I really hope so!

**Comment by tapir** [comment]
@steeve Is there any update on this?

**Comment by davux** [comment]
Curious too, and interested in seeing open sourced.

**Comment by ravishi** [comment]
For anyone interested, `steeve/pulsar` [1] has just been made public. I hope this means it's open sourced now :D

[1] https://github.com/steeve/pulsar

**Comment by tapir** [comment]
wow! thanks @steeve
