### ISSUE TITLE
Feature Request:  plugin://plugin.video.pulsar/search?query

### ISSUE THREAD

**Issue by mancuniancol** [steeve/plugin.video.pulsar#70]
I'd like to ask that search function in pulsar could use without keyboard. That, we can call it as it is possible with the play function:

plugin://plugin.video.pulsar/play?uri=magnet....

**Comment by steeve** [comment]
you can already:
`plugin://plugin.video.pulsar/search?q=<QUERY>`

**Comment by mancuniancol** [comment]
Thank you very much

**Comment by mancuniancol** [comment]
Steeve, I can use plugin://plugin.video.pulsar/movies/search?q=<QUERY>  and plugin://plugin.video.pulsar/shows/search?q=<QUERY>,
but I can't use plugin://plugin.video.pulsar/search?q=<QUERY>

I want to be able to search videos which aren't movies or tvshows. I am using Pulsar 0.4.3

Thanks.

**Comment by corrpel** [comment]
@mancuniancol did you manage to make it work?
What i am trying to achieve is search from any addon or library with a keymap, in the new quasar.
I configured it like this but it is giving me zero results:

ActivateWindow(10001,"plugin://plugin.video.quasar/movies/search?q=$INFO[ListItem.Title]")

Do you think i am doing something wrong?

**Comment by ghost** [comment]
Well, it is better that you contact the développer, it may be something changed
