### ISSUE TITLE
Por 4433 (and sometimes 4434)

### ISSUE THREAD

**Issue by gedl** [steeve/plugin.video.pulsar#98]
Hi,

This is more an question than actually a bug report.

I'm experiencing tremendously slow downloads while under a VPN. This does not happen with other torrent clients like Transmission.

I've setup and forwarded the configurable port but I noticed an extra port in the listen status: 4433 (sometimes 4434). 

So the question is: what is this port for? 

Another thing is, if this port is essential for proper torrent usage, is it configurable? I am unable to forward it under a VPN but I would be able to forward another one.

Thank you.

**Comment by steeve** [comment]
hi, sorry for the late reply

port `4433` might be used by libtorrent, although I'm not sure, however, as far as I'm concerned, Pulsar listens on `6889` to `7000` and `65252`

**Comment by gedl** [comment]
Ok thanks steeve.
